server:
  port: 8181
spring:
  application:
    name: @artifactId@
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  #国际化资源文件
  messages:
    basename: i18n/message,i18n/user_message
  web:
    resources:
      static-locations: classpath:static/
  redisson:
    file: classpath:redisson-config.yml


#okHttpClient配置
ok:
  http:
    #最大空闲连接数
    max-idle-connections: 500
    #保活持续时间 分钟
    keep-alive-duration: 5
    #以下单位 秒
    connect-timeout: 10
    read-timeout: 10
    write-timeout: 10

#coco配置
coco:
  # 请求L站 state 过期时间 分钟
  expirationTtl: 5
  #重定向地址
  redirectUri:
  clientId:
  clientSecret:
  #  L站
  authorizationEndpoint:
  tokenEndpoint:
  userEndpoint:
  #代理节点
  baseApi:
  baseProxy:
  #ghu 频率秒  1秒8次
  frequencyTime: 1
  #ghu频率数
  frequencyDegree: 8
  #用户基础频率  5分钟10次
  userRateTime: 5
  #用户基础频率数
  userFrequencyDegree: 15
  #用户token 有效期无请求接口 小时
  userTokenExpire: 1


#以下为风控参数
risk-contr:
  # 一个账号 一天能获取多少次Token
  getTokenNum: 10
  #单token 成功请求的最大数量 * 倍率 token失效
  tokenMaxReq: 500
  #每天用户最大请求数量 *倍率  限制 10小时 不可登陆
  userMaxReq: 2000
  userMaxTime: 10
  #超出用户最大访问速率 次数限制
  #10次 当前token失效
  tokenInvalidNum: 10
  #30次 限制 2小时 不可登陆
  rejectTimeNum: 30
  rejectTime: 2
  #200次 ban号级别
  banNum: 200

